### ISSUE TITLE
Allow parse_rate=0

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#14]
It should be possible to parse every single tick in a demo file. Useful for analysis of aiming behavior etc

**Comment by pnxenopoulos** [comment]
I think we can just change https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1639 to be `if currentFrameIdx == (currentGame.ParseRate - 1)` instead of what it currently is. @arjun-22 can fix.

**Comment by pnxenopoulos** [comment]
@adbok001 should be fixed in #22 by setting parse_rate=1. Thanks @arjun-22

**Comment by adbok001** [comment]
@pnxenopoulos Hi, this is not fixed, now parse_rate=2 gives the same results like parse_rate=1 before the change - so skipping every 2nd frame (expected behavior, I guess) - but parse_rate=1 now just sets Frames=null in the output json

**Comment by pnxenopoulos** [comment]
@adbok001 Woops. Should be fixed in the latest commit.

**Comment by adbok001** [comment]
@pnxenopoulos Hey, it's still not fixed. parse_rate=2 works fine, parse_rate=1 fails.

```
[...]/python/lib/python3.9/site-packages/csgo-0.1-py3.9.egg/csgo/parser/demoparser.py in __init__(self, demofile, outpath, log, demo_id, parse_rate)
     87         else:
     88             self.parse_rate = parse_rate
---> 89         self.logger.info("Setting parse rate to " + str(self.parse_rate))
     90 
     91         # Set parse error to False

AttributeError: 'DemoParser' object has no attribute 'parse_rate'
```

**Comment by pnxenopoulos** [comment]
@adbok001 oof...coding late at night...try now.

**Comment by adbok001** [comment]
@pnxenopoulos Works now it seems, thanks. #16 is still happening tho.
